module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/instrumenta/kubeval v0.0.0-20200414082145-45825b7caab9
	github.com/pkg/errors v0.8.1 // indirect
)
