apiVersion: v1
data:
  queries.yaml: |-
    "queries":
    - "name": "obervatorium-test-tenant"
      "query": "{observatorium=\"test\"}"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: e2e-test
    app.kubernetes.io/name: observatorium-up
    app.kubernetes.io/version: master-2020-09-28-120d857
  name: observatorium-up-logs
