jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: make fmt
      - run: make environments/dev/manifests
      - run: make validate

  tests:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: e2e tests
          no_output_timeout: 30m
          command : |
            make environments/dev/manifests
            make test-e2e
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  test-and-push:
    jobs:
      - build
      - tests
